[colors]
background       = '#2b3e50'
black            = '#a6b0b8'
blue             = '#72afe4'
cursor           = '#f0cc04'
cyan             = '#8be0fd'
foreground       = '#F8F8F2'
green            = '#46bd72'
magenta          = '#ca94ff'
red              = '#ff8878'
tabs             = '#72afe4'
tabs-active      = '#f0cc04'
white            = '#F8F8F2'
yellow           = '#f0cc04'
dim-black        = '#a6b0b8'
dim-blue         = '#7bb7eb'
dim-cyan         = '#6fb3ca'
dim-foreground   = '#dfdfd9'
dim-green        = '#46bd72'
dim-magenta      = '#cba2ff'
dim-red          = '#ff8878'
dim-white        = '#EFEFE1'
dim-yellow       = '#E6A003'
light-black      = '#a6b0b8'
light-blue       = '#D6ACFF'
light-cyan       = '#b9ecfd'
light-foreground = '#f8f8f2'
light-green      = '#72cc5a'
light-magenta    = '#d4a9ff'
light-red        = '#ff8878'
light-white      = '#FFFFFF'
light-yellow     = '#FFFFA5'
